Adding a search bar
mohamedrez/grh pull request #113
Opened 2023-05-30 09:19 UTC by itsAndL

2023-05-30 19:47 UTC, itsAndL commented
https://github.com/mohamedrez/grh/assets/105809250/70b6b774-4d92-47ef-a530-1984698bd18d

2023-05-30 19:49 UTC, mohamedrez requested changes
needs a small refactoring of the if else inside the erb instead you can add a css class "status-<%= 
 goal.status%>"
 and use the @apply in the tailwind

2023-05-30 19:49 UTC, mohamedrez commented on app/views/goals/_goal.html.erb
> +    <% if goal.status_incomplete? %>
This could be simplified using a css class instead of if and else

2023-05-30 19:49 UTC, mohamedrez commented on app/views/goals/_goal_attributes.html.erb
> +      <dd class="px-5 mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
Same thing here

2023-05-30 20:30 UTC, mohamedrez requested changes
small improvment is needed

2023-05-30 20:30 UTC, mohamedrez commented on app/assets/stylesheets/application.tailwind.css
> +.status {
status is very generic name can you make it goal-status please

2023-05-30 20:34 UTC, itsAndL commented on app/assets/stylesheets/application.tailwind.css
> +.status {
got it

2023-05-31 09:04 UTC, mohamedrez reviewed
simplify goal status

2023-05-31 13:26 UTC, mohamedrez approved these changes

2023-05-31 13:26 UTC, merged