Add Job application
mohamedrez/grh pull request #148
Opened 2023-06-15 09:49 UTC by MehdiElrafi

2023-06-15 10:57 UTC, mohamedrez requested changes
Migrations are wrong. the schema.rb is not reflecting the changes

2023-06-15 10:57 UTC, mohamedrez commented on db/migrate/20230613095647_add_payment_type_to_mission_orders.rb
> -class AddPaymentTypeToMissionOrders < ActiveRecord::Migration[7.0]
Why did you delete this file ?

2023-06-15 10:57 UTC, mohamedrez commented on db/migrate/20230614084437_add_attachment_to_job_application.rb
> +    add_column :job_applications, :attachment, :blob
No need for attach

2023-06-15 11:15 UTC, MehdiElrafi commented on db/migrate/20230613095647_add_payment_type_to_mission_orders.rb
> -class AddPaymentTypeToMissionOrders < ActiveRecord::Migration[7.0]
by mistake, how I can restore it ?

2023-06-15 19:09 UTC, mohamedrez requested changes

2023-06-15 19:09 UTC, mohamedrez commented on db/schema.rb
> +  create_table "posts", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
why do you have posts in this migration?

2023-06-15 19:12 UTC, MehdiElrafi commented on db/schema.rb
> +  create_table "posts", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
No

2023-06-15 19:13 UTC, MehdiElrafi commented on db/schema.rb
> +  create_table "posts", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
Emmm Yeah Yeah I create a posts table to apply an example of attach file but I do it in new branch and I delete the branch after

2023-06-16 09:04 UTC, mohamedrez requested changes

2023-06-16 09:04 UTC, mohamedrez commented on config/environments/production.rb
> +    open_timeout: 5,
Why is there a change in the production.rb ?

2023-06-16 09:09 UTC, MehdiElrafi commented on config/environments/production.rb
> +    open_timeout: 5,
![Screenshot 2023-06-15 164506](https://github.com/mohamedrez/grh/assets/134804467/c5495678-6dbe-45b5-b4c4-6a794a8435ac)
Because of this error,  I make enable_starttls_auto's key at the end and I remove the comma then the problem is resolved

2023-06-16 12:24 UTC, mohamedrez requested changes

2023-06-16 12:24 UTC, mohamedrez commented on config/environments/production.rb
> +    open_timeout: 5,
but you are not only adding removing the comma you added open_timeout and read time_out

2023-06-16 13:39 UTC, MehdiElrafi commented on config/environments/production.rb
> +    open_timeout: 5,
I'm really surprised, I don't know how but trust me I don't add anything in this file, I'm so sorry for that.
I'll remove this two keys. Thank you @mohamedrez

2023-06-16 14:29 UTC, mohamedrez approved these changes

2023-06-16 14:29 UTC, merged