Add the ability to manger to see his team
mohamedrez/grh pull request #158
Opened 2023-06-18 12:57 UTC by itsAndL

![image](https://github.com/mohamedrez/grh/assets/105809250/2f2f945c-f9c2-4a76-8c28-d212618ce3d7)

2023-06-19 11:54 UTC, mohamedrez requested changes

2023-06-19 11:54 UTC, mohamedrez commented on app/controllers/users_controller.rb
> +    @q = if request.path.include?("my_team")
can you make manager_id= instead

2023-06-19 13:22 UTC, itsAndL commented on app/controllers/users_controller.rb
> +    @q = if request.path.include?("my_team")
can you explain it more

2023-06-20 08:51 UTC, mohamedrez approved these changes

2023-06-20 08:53 UTC, mohamedrez requested changes

2023-06-20 08:53 UTC, mohamedrez commented on app/models/user.rb
> +  def has_any_subordinates?
we don't need subordinates it is a nice to have but it will fire a sql query on every page refresh

2023-06-20 13:24 UTC, merged