Modifying all things associated with settings page
mohamedrez/grh pull request #162
Opened 2023-06-19 12:08 UTC by itsAndL

2023-06-19 12:16 UTC, itsAndL commented
![Screenshot 2023-06-19 130859](https://github.com/mohamedrez/grh/assets/105809250/85685bb9-2c9e-48b1-bf08-4ac3eecb4e7b)

2023-06-19 12:20 UTC, itsAndL commented
@mohamedrez. if you notice at this point i'm not using the settings page, but instead just showing the pages for (roles, sites, holidays)

2023-06-19 16:03 UTC, mohamedrez requested changes

2023-06-19 16:03 UTC, mohamedrez commented on app/models/role.rb
> +  enum name: {admin: 0, hr: 1, accountant: 2, manager: 3}
Why is this change needed ?

2023-06-19 16:23 UTC, itsAndL commented on app/models/role.rb
> +  enum name: {admin: 0, hr: 1, accountant: 2, manager: 3}
i just wanna put admin in the first of select menu

2023-06-19 18:18 UTC, mohamedrez requested changes

2023-06-19 18:18 UTC, mohamedrez commented on app/policies/admin_hr_policy.rb
> +class AdminHrPolicy < ApplicationPolicy
Can you avoid inhertiance and instead use composition?

2023-06-20 13:21 UTC, mohamedrez approved these changes

2023-06-20 13:22 UTC, merged