Job  link
mohamedrez/grh pull request #181
Opened 2023-06-22 15:15 UTC by achrafbsibiss

2023-06-26 10:39 UTC, mohamedrez requested changes

2023-06-26 10:39 UTC, mohamedrez commented on app/views/job_applications/_form.html.erb
> +          <%= form.label :resume, t("attributes.job_application.attach_a_receipt") %>
why is it a receipt ?

2023-06-26 20:52 UTC, achrafbsibiss commented on app/views/job_applications/_form.html.erb
> +          <%= form.label :resume, t("attributes.job_application.attach_a_receipt") %>
it's just by fault, sorry

2023-06-27 09:53 UTC, mohamedrez approved these changes

2023-07-03 16:10 UTC, mohamedrez requested changes

2023-07-03 16:10 UTC, mohamedrez commented on Gemfile
> +  gem "rails-controller-testing"
why we had to add this new gem ?

2023-07-03 16:28 UTC, achrafbsibiss commented on Gemfile
> +  gem "rails-controller-testing"
this  i do the  "bundle exec rspec ./spec/requests/job_application_spec.rb"  he can check for the layout

2023-07-04 15:54 UTC, itsAndL approved these changes

2023-07-05 11:14 UTC, itsAndL commented on app/controllers/job_applications_controller.rb
> +  before_action :set_breadcrumbs, only: :index
need to get it back to the previous one

2023-07-05 11:16 UTC, itsAndL requested changes
get things back that will not make an effect

2023-07-06 10:57 UTC, closed without merging