Job application customizing code
mohamedrez/grh pull request #208
Opened 2023-07-03 10:32 UTC by MehdiElrafi

2023-07-03 11:49 UTC, MehdiElrafi commented
Before: 
![Screenshot_2023-07-03_12-46-27](https://github.com/mohamedrez/grh/assets/134804467/6216f8d0-4aab-4821-bd76-2b91cbe2240f)
After:
![Screenshot_2023-07-03_12-35-13](https://github.com/mohamedrez/grh/assets/134804467/18ce1d0f-f834-4470-9b7a-2a771d552b5c)

2023-07-03 12:48 UTC, MehdiElrafi commented
Before : 
![Screenshot_2023-07-03_12-46-27](https://github.com/mohamedrez/grh/assets/134804467/075ff74c-4186-4681-a2b2-6212c51a3103)
After : 
![Screenshot_2023-07-03_13-47-45](https://github.com/mohamedrez/grh/assets/134804467/f5cec4aa-ec83-41f1-a940-d43f7aeba524)

2023-07-03 13:00 UTC, mohamedrez requested changes

2023-07-03 13:00 UTC, mohamedrez commented on app/models/job_application.rb
> +  def job_present(job_id, job_application_id, next_state = "")
this naming is not meaninful, the function name should describe better the code that it wraps

2023-07-03 13:00 UTC, mohamedrez commented on app/views/job_applications/_right_side.html.erb
>                        case aasm_log.to_state
no case inside the view.

2023-07-04 12:04 UTC, mohamedrez approved these changes

2023-07-04 12:20 UTC, merged