add style to open and close job
mohamedrez/grh pull request #213
Opened 2023-07-05 10:25 UTC by MehdiElrafi

2023-07-06 10:22 UTC, MehdiElrafi commented
![Screenshot_2023-07-06_11-22-16](https://github.com/mohamedrez/grh/assets/134804467/6ab47d40-9f93-4ad6-8a5f-4c73b1b06c19)

2023-07-06 11:23 UTC, mohamedrez requested changes

2023-07-06 11:23 UTC, mohamedrez commented on app/models/job.rb
> +  def color_badge(status)
You don't need color_badge instead you could print job-status<%= job.status %> and play with it in the CSS

2023-07-07 16:35 UTC, mohamedrez approved these changes

2023-07-07 17:00 UTC, merged