Mailing process for the requestables
mohamedrez/grh pull request #235
Opened 2023-07-12 10:49 UTC by itsAndL

2023-07-12 12:24 UTC, mohamedrez requested changes

2023-07-12 12:24 UTC, mohamedrez commented on db/schema.rb
> +  create_table "courses", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
This should not be here

2023-07-14 10:03 UTC, itsAndL commented
![Screenshot 2023-07-14 102505](https://github.com/mohamedrez/grh/assets/105809250/17e915b5-2884-42de-b304-92a8ae129ce5)

2023-07-14 10:04 UTC, itsAndL commented
![image](https://github.com/mohamedrez/grh/assets/105809250/dc01e115-fa6f-4d9c-93bd-7e59d35331d5)

2023-07-14 12:15 UTC, mohamedrez approved these changes

2023-07-14 17:00 UTC, merged