Working on tasks in Dashbord
mohamedrez/grh pull request #236
Opened 2023-07-12 13:57 UTC by achrafbsibiss

2023-07-12 15:07 UTC, itsAndL commented on app/controllers/dashboard_controller.rb
> +    @tasks = current_user.task
current_user.tasks

in the models/user.rb
has_many :tasks, dependent: :destroy
not
has_many :task, dependent: :destroy

2023-07-17 13:10 UTC, mohamedrez requested changes

2023-07-17 13:10 UTC, mohamedrez commented on app/controllers/dashboard_controller.rb
> +    @tasks = current_user.tasks
Only the ones that are active

2023-07-17 13:11 UTC, mohamedrez commented
needs to fix tests, also not all the tasks the member can mark as complete so there is no need for the select box in the corner

2023-07-17 16:58 UTC, achrafbsibiss commented on app/controllers/dashboard_controller.rb
> +    @tasks = current_user.tasks
can you explain it more

2023-07-24 16:11 UTC, mohamedrez approved these changes

2023-07-24 16:12 UTC, merged