Show number of Pto taken
mohamedrez/grh pull request #238
Opened 2023-07-12 15:18 UTC by MehdiElrafi

2023-07-12 15:25 UTC, MehdiElrafi commented
![Screenshot_2023-07-12_16-25-03](https://github.com/mohamedrez/grh/assets/134804467/aec624ac-46a8-4d5f-bb56-83dcd1ddac01)

2023-07-13 09:35 UTC, mohamedrez requested changes

2023-07-13 09:35 UTC, mohamedrez commented on app/controllers/time_requests_controller.rb
> +        turbo_stream.replace("days_per_year", partial: "time_requests/days_per_year", locals: {user_id: current_user.id}),
we don't want only to show it in the create, it needs to be shown on the user profile page

2023-07-13 09:35 UTC, mohamedrez commented on app/models/time_request.rb
> +  def self.number_of_days_taken_per_year(user_id)
I will have this one simplified this is doing more than one thing wich breaks the single responsability principle.

You can have a function: 
- holiday_days : this will return [01/01/2023, 11/01/2023 ...]
- format_time_requests: [{day: '01/01/2023', request_type: 'pto' }]
- calculate_days_off_taken: uses holiday_days if the date is present in there it will not count it

2023-07-14 12:01 UTC, MehdiElrafi commented
![Screenshot_2023-07-14_13-01-08](https://github.com/mohamedrez/grh/assets/134804467/b573b4b5-d7c8-455d-b75b-1d8c94f0d0db)

2023-07-14 12:18 UTC, mohamedrez approved these changes

2023-07-14 13:38 UTC, merged