Ability to add new expense from mission_order
mohamedrez/grh pull request #255
Opened 2023-07-18 09:21 UTC by itsAndL

2023-07-18 09:24 UTC, itsAndL commented
# Index
![Screenshot 2023-07-18 102220](https://github.com/mohamedrez/grh/assets/105809250/3a1277d0-8117-48a1-934b-461eebc60d89)


# show
![Screenshot 2023-07-18 102242](https://github.com/mohamedrez/grh/assets/105809250/df6497f8-ffa8-4767-9ade-7a0b7df6fea9)

2023-07-18 13:24 UTC, mohamedrez requested changes
Add expense button should be inside the show page and not in the listing page

2023-07-19 14:44 UTC, itsAndL commented
![image](https://github.com/mohamedrez/grh/assets/105809250/4db32eb7-1e01-4576-a2e9-98a264ee6bc3)

2023-07-19 18:09 UTC, mohamedrez approved these changes

2023-07-19 18:09 UTC, merged