Fix calcule pto number bug
mohamedrez/grh pull request #289
Opened 2023-08-08 17:06 UTC by MehdiElrafi

2023-08-09 17:48 UTC, mohamedrez requested changes

2023-08-09 17:48 UTC, mohamedrez commented on app/controllers/time_requests_controller.rb
> +      @time_request.user.update(pto_number: @time_request.user.pto_number - (@time_request.end_date - @time_request.start_date).to_i)
can you move this logic in a model active record callback

2023-08-11 14:14 UTC, itsAndL approved these changes

2023-08-11 14:27 UTC, itsAndL approved these changes

2023-08-11 15:14 UTC, mohamedrez approved these changes

2023-08-11 15:14 UTC, merged