Site model
mohamedrez/grh pull request #32
Opened 2023-04-12 15:26 UTC by itsAndL

working on site model

2023-04-12 17:26 UTC, mohamedrez requested changes
also make sure to include a seed file for all sites

2023-04-12 17:26 UTC, mohamedrez commented on db/migrate/20230412131645_create_sites.rb
> +      t.references :user, null: false, foreign_key: true
There shouldn't be a reference here, a user  should belong to a site and a site has many users
the reference should be site_id in the users table

2023-04-12 17:26 UTC, mohamedrez commented on app/models/site.rb
> +  enum :name, %i[CCAB CIOC CJO HPC CMCL VINCI], prefix: :user
if those are the code then instead of using the name field add code field to sites

2023-04-12 18:39 UTC, itsAndL commented on app/models/site.rb
> +  enum :name, %i[CCAB CIOC CJO HPC CMCL VINCI], prefix: :user
you can now check the commit after this commit, I make a lot of changes,

2023-04-13 15:34 UTC, mohamedrez requested changes

2023-04-13 15:34 UTC, mohamedrez commented on app/controllers/users_controller.rb
> +    @site = @user.site || @user.build_site
here You only need the site_id, you don't need to build the site

2023-04-13 15:34 UTC, mohamedrez commented on app/models/user.rb
> +  accepts_nested_attributes_for :site, update_only: true
No need for accepts_nested_attributes_for

2023-04-13 15:34 UTC, mohamedrez commented on app/views/users/edit.html.erb
> +                <%= f.select :name, options_for_select(Site.pluck(:name, :name)), {}, { class: "w-full" } %>
Here it should be :name and :id  not name name

2023-04-13 15:34 UTC, mohamedrez commented on db/csv/sites_akdital.csv
> +"CMCL","Medico Surgical Clinic Longchamps","4,Bd Ghandi, Casablanca","05 22 04 07 07"
we shouldn't leak this information on the web this file needs to be removed

2023-04-13 15:34 UTC, mohamedrez commented on db/migrate/20230412160959_modify_sites_table.rb
> +    remove_reference :sites, :user, foreign_key: true
Instead of creating a new migration to change due to a review you need to do a rails db:rollback to undo the last migration and modify the last migration file

2023-04-13 15:34 UTC, mohamedrez commented on db/migrate/20230412163240_add_site_ref_to_users.rb
> +    add_reference :users, :site, null: false, foreign_key: true
remove null false, to allow a user to not have a site

2023-04-13 15:34 UTC, mohamedrez commented on db/seeds.rb
> +ImportCsvHelper.import_sites_akdital
we don't need real data just create some random sites

2023-04-13 15:34 UTC, mohamedrez commented on spec/factories/sites.rb
> +    name { "Akdital Headquarters" }
let's keep things secret we don't want akdital on anything

2023-04-13 22:49 UTC, mohamedrez requested changes
Needs few changes and test in the controller of updating a users site

2023-04-13 22:49 UTC, mohamedrez commented on app/models/site.rb
> +  has_many :user, dependent: :destroy
we don't want to destroy a user if we remove a site or vice versa

2023-04-13 22:49 UTC, mohamedrez commented on spec/factories/users.rb
> +    if Rails.env.development?
No need for this, factories should be used mainly with Rspec

2023-04-14 07:28 UTC, mohamedrez approved these changes

2023-04-14 07:57 UTC, merged