time off detail page
mohamedrez/grh pull request #35
Opened 2023-04-16 10:50 UTC by itsAndL

2023-04-17 13:37 UTC, mohamedrez requested changes

2023-04-17 13:37 UTC, mohamedrez commented on app/controllers/user_requests_controller.rb
> +      @user_request.update(managed_by_id: params[:managed_by_id], state: :approved)
managed_by should be the current logged in user

2023-04-17 13:44 UTC, itsAndL commented on app/controllers/user_requests_controller.rb
> +      @user_request.update(managed_by_id: params[:managed_by_id], state: :approved)
so in the show view of the TimeOffRequest, there's this link
and if you can see, is the current user
user_user_request_update_path(user_id: @user.id, id: @user_request.id, managed_by_id: current_user.id, state: :rejected)

2023-04-17 14:03 UTC, itsAndL commented on app/models/time_off_request.rb
> +  def who_else_be_out?
can you explain this one

2023-04-19 07:03 UTC, mohamedrez commented on app/controllers/user_requests_controller.rb
> +    if params[:state] == "approved"
there is no need for this conditionnal

2023-04-19 07:05 UTC, mohamedrez approved these changes

2023-04-19 07:08 UTC, itsAndL commented on app/controllers/user_requests_controller.rb
> +    if params[:state] == "approved"
I have 2 buttons

<%= button_to "Approve", user_user_request_update_path(user_id: @user.id, id: @user_request.id, state: :approved), method: :patch %>

<%= button_to "Deny", user_user_request_update_path(user_id: @user.id, id: @user_request.id, state: :rejected), method: :patch%>

as you can see I passed ( state ), so that represents the type

2023-04-19 07:15 UTC, itsAndL commented on app/controllers/user_requests_controller.rb
> +    if params[:state] == "approved"
you can check this commit 
https://github.com/mohamedrez/grh/pull/35/commits/7460f1956a095482e7edf6a2886e57996a1b1550

2023-04-19 07:17 UTC, merged