change inactive contracts query
mohamedrez/grh pull request #419
Opened 2023-09-20 11:25 UTC by MehdiElrafi

2023-09-20 11:25 UTC, MehdiElrafi commented
![](https://github.trello.services/images/mini-trello-icon.png) [When i try to edit an employee information, an error is displayed](https://trello.com/c/jooG0L1t/196-when-i-try-to-edit-an-employee-information-an-error-is-displayed)

2023-09-20 17:05 UTC, mohamedrez requested changes

2023-09-20 17:05 UTC, mohamedrez commented on app/views/users/_form.html.erb
> +                  <% inactive_contracts = @contracts.where.not(id: @contracts.last).order(:created_at) %>
I don't think this should  be handled in the view, what do you mean by inactive contract

2023-09-21 08:33 UTC, MehdiElrafi commented on app/views/users/_form.html.erb
> +                  <% inactive_contracts = @contracts.where.not(id: @contracts.last).order(:created_at) %>
In the Contract model I store the history of user's contracts, I display this history above contract form (Inactive contracts means all contracts excluding last one)

2023-09-21 15:42 UTC, mohamedrez commented on app/views/users/_form.html.erb
> +                  <% inactive_contracts = @contracts.where.not(id: @contracts.last).order(:created_at) %>
you need a field status in the DB for the contract that sets it to innactive automantically, and sets the new one to actif

2023-09-25 13:38 UTC, mohamedrez requested changes

2023-09-25 13:38 UTC, mohamedrez commented on db/schema.rb
> +    t.bigint "service_id", null: false
is this migration supposed to be here ?

2023-09-25 13:46 UTC, MehdiElrafi commented on db/schema.rb
> +    t.bigint "service_id", null: false
It's my bad ! I will resolve that

2023-09-25 16:44 UTC, mohamedrez approved these changes

2023-09-25 16:46 UTC, merged