Filtering users
mohamedrez/grh pull request #422
Opened 2023-09-20 15:38 UTC by itsAndL

2023-09-20 15:46 UTC, itsAndL commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add filter to employee page (Team tab) to be able to filtrate "employees under my responsability" and "employees in my team"](https://trello.com/c/1qd1CI2F/203-add-filter-to-employee-page-team-tab-to-be-able-to-filtrate-employees-under-my-responsability-and-employees-in-my-team)

2023-09-20 16:44 UTC, mohamedrez requested changes

2023-09-20 16:44 UTC, mohamedrez commented on config/credentials.yml.enc
> -piUBO8z53KtSDg9fmOvrtmldq2YNPK5h7mW7c6ObZsN+JtJOkuJqtfPuVJfWiQT+DJLyw9BMpAgIHeJK+x4+452fwhNZbaLQX5Q2oF5ug99Yl9f8RA+Ki+w830/kk16X3117eV8CQNgRHj5G9+NCHQTIvHLEWABaSIJe96VkNKn4/stSTmYpkqi82vAU/H5+zNAIBFo
was is supposed to be a change here ?

2023-09-21 08:31 UTC, itsAndL commented
![image](https://github.com/mohamedrez/grh/assets/105809250/b884205f-1fbe-4a4e-91fa-4a02cf62d36d)

2023-09-21 10:43 UTC, mohamedrez approved these changes

2023-09-21 11:53 UTC, merged