Initial work on setting host dynamically
mohamedrez/grh pull request #467
Opened 2023-10-05 16:12 UTC by itsAndL

2023-10-05 16:33 UTC, itsAndL commented
@mohamedrez, setting the ENV variables in ApplicationController it's not working

2023-10-05 19:01 UTC, mohamedrez requested changes

2023-10-05 19:01 UTC, mohamedrez commented on app/controllers/application_controller.rb
> +    ENV["HOST_WITH_PORT"] = request.host_with_port
does not wrok ENV should not be set in the code

2023-10-06 10:48 UTC, itsAndL commented
@mohamedrez i overload the environment variables in action mailer
but with Devise and routes.rb file, it's not working

2023-10-06 11:23 UTC, itsAndL commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change password is not working for akdital.humaneo.ma (the link root is wrong : uat.humaneo)](https://trello.com/c/87Q2NfeE/217-change-password-is-not-working-for-akditalhumaneoma-the-link-root-is-wrong-uathumaneo)

2023-10-06 14:25 UTC, itsAndL commented on config/initializers/devise.rb
> +  config.mailer_sender = "no-reply@#{ENV["HOST_WITH_PORT"]}"
@mohamedrez  this one stay with the default value

2023-10-06 15:37 UTC, mohamedrez requested changes

2023-10-06 15:37 UTC, mohamedrez commented on config/environments/production.rb
> +ENV["HOST_WITH_PORT"] ||= "uat.humaneo.ma:8800"
not needed we can add those inside the machine

2023-10-09 10:04 UTC, closed without merging

2023-10-09 10:04 UTC, mohamedrez commented
ref https://github.com/mohamedrez/grh/pull/477