fixed NaN% in the progress evaluation after deleting user from app
mohamedrez/grh pull request #531
Opened 2023-10-26 12:39 UTC by Mouados-byte

2023-10-26 14:14 UTC, mohamedrez approved these changes

2023-10-27 08:40 UTC, mohamedrez requested changes

2023-10-27 08:40 UTC, mohamedrez commented on app/views/group_evaluations/_group_evaluation.html.erb
> +    <%= record.users.count != 0 ? (record&.evaluation&.evaluation_responses&.count.to_f  / record.users.count).round(2) * 100 : 0.to_f %>%
Can you move this logic to helper in the controller ?

2023-10-27 19:00 UTC, Mouados-byte commented on app/views/group_evaluations/_group_evaluation.html.erb
> +    <%= record.users.count != 0 ? (record&.evaluation&.evaluation_responses&.count.to_f  / record.users.count).round(2) * 100 : 0.to_f %>%
but its related to the record , each record of the list

2023-10-28 12:25 UTC, Mouados-byte commented on app/views/group_evaluations/_group_evaluation.html.erb
> +    <%= record.users.count != 0 ? (record&.evaluation&.evaluation_responses&.count.to_f  / record.users.count).round(2) * 100 : 0.to_f %>%
Fixed it , but as a method in the model

2023-10-30 09:59 UTC, merged