Adding filters to settings
mohamedrez/grh pull request #687
Opened 2023-12-14 13:25 UTC by Mouados-byte

# Roles:

![image](https://github.com/mohamedrez/grh/assets/74561965/efcda774-b7b8-4b84-b2e7-c8cf37b771b2)

# Sites:

![image](https://github.com/mohamedrez/grh/assets/74561965/6b6f605e-57da-4164-8b26-b164b14bfb4c)

# Services:

![image](https://github.com/mohamedrez/grh/assets/74561965/c9cab229-c319-42e8-8b30-bb1f53fc7153)

# Holidays:

![image](https://github.com/mohamedrez/grh/assets/74561965/e02fa1c3-4cdc-425f-b076-7577ffc0c1a2)

2023-12-14 13:48 UTC, Mouados-byte commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Filters to all parameters tabs => we have lists without search filters](https://trello.com/c/ffWDxkFs/272-add-filters-to-all-parameters-tabs-we-have-lists-without-search-filters)

2023-12-15 16:16 UTC, itsAndL requested changes

2023-12-15 16:16 UTC, itsAndL commented on app/views/sites/index.html.erb
> +      <%= search_form_for @q, method: :get, url: @url, data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit" } do |f| %>
for sites you can do all the filters in one filter

2023-12-15 16:16 UTC, itsAndL commented on app/views/services/index.html.erb
> +      <%= search_form_for @q, method: :get, url: @url, data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit" } do |f| %>
you can put the search directly in the index page

bo beed the filter dropdown, cause you filter by one

2023-12-15 16:27 UTC, itsAndL commented on app/views/roles/index.html.erb
> +            <%= f.label :user_first_name_or_last_name_or_email_cont, class: "sr-only", placeholder:t("views.roles.search_by") %>
Filter for role already exist

2023-12-15 16:30 UTC, MehdiElrafi commented on app/views/roles/index.html.erb
> +            <%= f.label :user_first_name_or_last_name_or_email_cont, class: "sr-only", placeholder:t("views.roles.search_by") %>
why you add filter by email?
and I won't able to filter by last_name you need to user_first_name_or_user_last_name_cont!
also for selecting roles in filter you need to make it by current user role (if current user has role hr he won't able to filter by admins, check roles_names_to_select() method in role model)

2023-12-15 16:50 UTC, Mouados-byte commented on app/views/sites/index.html.erb
> +      <%= search_form_for @q, method: :get, url: @url, data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit" } do |f| %>
what about the code ?

2023-12-15 17:10 UTC, Mouados-byte commented on app/views/services/index.html.erb
> +      <%= search_form_for @q, method: :get, url: @url, data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit" } do |f| %>
Done

2023-12-15 17:11 UTC, Mouados-byte commented on app/views/roles/index.html.erb
> +            <%= f.label :user_first_name_or_last_name_or_email_cont, class: "sr-only", placeholder:t("views.roles.search_by") %>
Done

2023-12-15 20:12 UTC, MehdiElrafi approved these changes

2023-12-19 14:24 UTC, itsAndL approved these changes

2023-12-19 14:26 UTC, merged