Adding both charts
mohamedrez/grh pull request #694
Opened 2023-12-15 15:58 UTC by Mouados-byte

# First Chart: Monthly Employee Turnover and Movement

![image](https://github.com/mohamedrez/grh/assets/74561965/39804626-2644-4164-b023-4dea3cc7488c)

# Second Chart: Employee Departure Reasons

![image](https://github.com/mohamedrez/grh/assets/74561965/31928d25-b085-434b-8541-8080b1908b39)

2023-12-15 16:31 UTC, itsAndL requested changes

2023-12-15 16:31 UTC, itsAndL commented on app/controllers/charts_controller.rb
> +  def quit_reasons_chart
Put business logic in a service

2023-12-15 17:13 UTC, Mouados-byte commented
![](https://github.trello.services/images/mini-trello-icon.png) [In statistics, add a graph that displays number of people who quit the company VS People who join it each month for the current year, display also the "Turn Over" pourcentage](https://trello.com/c/MdNoTlhm/273-in-statistics-add-a-graph-that-displays-number-of-people-who-quit-the-company-vs-people-who-join-it-each-month-for-the-current-y)

2023-12-16 16:48 UTC, Mouados-byte commented on app/controllers/charts_controller.rb
> +  def quit_reasons_chart
Done

2023-12-21 13:29 UTC, itsAndL approved these changes

2023-12-21 18:56 UTC, merged