Working on the Announcement part
mohamedrez/grh pull request #71
Opened 2023-05-03 14:45 UTC by achrafbsibiss

2023-05-04 19:58 UTC, mohamedrez requested changes

2023-05-04 19:58 UTC, mohamedrez commented on app/views/announcements/index.html.erb
> + <%=link_to "Creat new Announcement", new_announcement_path, class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
Create instead of Creat and can you wrap it inside translation helper

2023-05-04 19:58 UTC, mohamedrez commented on app/views/announcements/_form.html.erb
> +    <div>
Can you make the indentation 2 instead of 4

2023-05-04 19:58 UTC, mohamedrez commented on app/views/announcements/new.html.erb
> +<h1 class="mt-4">Add new Event</h1>
Announcement instead of Event

2023-05-04 19:58 UTC, mohamedrez commented on app/views/dashboard/index.html.erb
> +                          <%=link_to announcement.title.titleize, announcement_path(announcement.id) , class:"hover:underline focus:outline-none"%>
Can you clean up unused comments

2023-05-04 19:58 UTC, mohamedrez commented on app/views/dashboard/index.html.erb
> +                <%=link_to "View all" ,announcements_path , class: "flex w-full items-center justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-ins
View all needs to be translatable

2023-05-05 05:11 UTC, itsAndL requested changes

2023-05-05 05:11 UTC, itsAndL commented on app/controllers/announcements_controller.rb
> +      render "edit", status: :unprocessable_entity
this line didn't yet cover by the test

2023-05-05 12:11 UTC, merged