Feature update pto
mohamedrez/grh pull request #730
Opened 2023-12-29 17:11 UTC by MounirGaiby

2023-12-29 17:16 UTC, MounirGaiby commented
![Screenshot 2023-12-29 181613](https://github.com/mohamedrez/grh/assets/77928247/4db576e7-614e-4951-ade6-15b0cdc008e2)

2024-01-09 17:21 UTC, MehdiElrafi requested changes

2024-01-09 17:21 UTC, MehdiElrafi commented on app/controllers/time_requests_controller.rb
> +  def time_request_reduction_amount(time_preference_for_start_date, time_preference_for_end_date, start_date, end_date, employee_schedule)
Move this one to time_request.rb

2024-01-09 17:21 UTC, MehdiElrafi commented on app/helpers/date_helper.rb
> +module DateHelper
Remove this one

2024-01-09 17:41 UTC, MehdiElrafi approved these changes

2024-01-09 17:41 UTC, merged