Fixed the filter count + second menu content fetching
mohamedrez/grh pull request #795
Opened 2024-01-17 20:08 UTC by Mouados-byte

2024-01-17 20:09 UTC, Mouados-byte commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effectuer un contrôle sur les filtres existants relatifs aux sites](https://trello.com/c/oAFZR6iE/329-effectuer-un-contr%C3%B4le-sur-les-filtres-existants-relatifs-aux-sites)

2024-01-17 21:35 UTC, MehdiElrafi requested changes

2024-01-17 21:35 UTC, MehdiElrafi commented on app/javascript/controllers/dynamic_select_controller.js
> +  siteChanged() {
Oops!

2024-01-17 22:07 UTC, MehdiElrafi commented
Fix this css bugs please:
![image](https://github.com/mohamedrez/grh/assets/134804467/fcc22302-40e6-47d2-9fc9-ddb715f18126)
remove the margin:
![image](https://github.com/mohamedrez/grh/assets/134804467/81c96c0e-1453-4d42-b327-8781a26e7b36)

2024-01-18 14:14 UTC, Mouados-byte commented on app/javascript/controllers/dynamic_select_controller.js
> +  siteChanged() {
Debugging moments

2024-01-18 20:59 UTC, MehdiElrafi approved these changes

2024-01-18 21:25 UTC, merged