Initial work on the Expense resource
mohamedrez/grh pull request #99
Opened 2023-05-18 19:31 UTC by itsAndL

2023-05-22 11:50 UTC, itsAndL commented
https://github.com/mohamedrez/grh/assets/105809250/d20f67a4-1c38-4387-8e83-046a7dd098ee

2023-05-23 17:21 UTC, mohamedrez commented on app/models/expense.rb
> +  enum :category, ["--None--", "Travel Expenses", "Meal and Entertainment Expenses", "Training and Development Expenses", "Office Supplies and Equipment Expenses", "Recruitment Expenses", "Employee B
needs translation

2023-05-23 17:25 UTC, mohamedrez commented on app/models/expense.rb
> +  def receipts=(attachables)
I am not able to understand why do we need this code

2023-05-23 17:25 UTC, mohamedrez commented on app/models/expense.rb
> +  def attachment_exists?(attachment)
also for this part what was the issue that you faced and you had to do it this way

2023-05-23 17:26 UTC, mohamedrez requested changes
I left some comments

2023-05-24 06:19 UTC, itsAndL commented on app/models/expense.rb
> +  def receipts=(attachables)
is the only way that I can keep the old uploaded files when updating an existing Expense.

2023-05-24 06:25 UTC, itsAndL commented on app/models/expense.rb
> +  def attachment_exists?(attachment)
this method checks if the uploaded file exists. so that we cannot have duplicate files

2023-05-24 07:26 UTC, itsAndL commented on app/models/expense.rb
> +  enum :category, ["--None--", "Travel Expenses", "Meal and Entertainment Expenses", "Training and Development Expenses", "Office Supplies and Equipment Expenses", "Recruitment Expenses", "Employee B
Now you can review this commit
https://github.com/mohamedrez/grh/pull/99/commits/dbde17811753bd8e68f0e72903724b57dd9e011b

2023-05-24 16:48 UTC, mohamedrez approved these changes

2023-05-24 16:49 UTC, merged